name: Facturas

on:
  schedule:
    - cron: '0 * * * *'   # Se ejecuta cada hora (ajusta según tus necesidades)
  workflow_dispatch:      # Permite ejecutar el workflow manualmente

jobs:
  run-and-send:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      EXCEL_FILE_PATH: ${{ secrets.EXCEL_FILE_PATH }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Enviar archivo a Power Automate
        run: |
          curl -X POST "https://prod-174.westeurope.logic.azure.com:443/workflows/577f204a906a450b9d2964640073bab5/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=gfKa0Yp0vILrw5KENggyypz5MZHuuEHaU0ot1Ov9s_Q" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@${{ env.EXCEL_FILE_PATH }}"
